language: python
python:
  - "3.5"

notifications:
  email: false
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script:
  - ./runTests.sh
  - coverage run sainsburys/main.py tests/
after_success:
    - coveralls --rcfile=.coveragerc
